### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by richardschneider** [libp2p/js-libp2p-kad-dht#24]
These tests are failing
```
1) RoutingTable add:
     Uncaught Error: Callback was already called.
      at node_modules\async\internal\onlyOnce.js:9:32
      at Timeout.timeoutCallback [as _onTimeout] (node_modules\async\timeout.js:74:13)
  2) rpc - handlers - AddProvider "before all" hook:
     Uncaught TypeError: Cannot read property 'isPending' of undefined
      at PeerId.create (test\routing.spec.js:26:7)
      at waterfall (node_modules\peer-id\src\index.js:146:5)
      at node_modules\async\internal\once.js:12:16
      at next (node_modules\async\waterfall.js:21:29)
      at node_modules\async\internal\onlyOnce.js:12:16
      at privKey.public.hash (node_modules\peer-id\src\index.js:139:7)
      at Multihashing.Multihashing.digest (node_modules\multihashing-async\src\index.js:33:5)
      at setImmediate (node_modules\multihashing-async\src\utils.js:8:7)
      at Immediate._onImmediate (node_modules\async\internal\setImmediate.js:27:16)
```

**Comment by diasdavid** [comment]
fixed in https://github.com/libp2p/js-libp2p-kad-dht/pull/25
