### ISSUE TITLE
Error when calling contentRouter.provide(): "Unknown type, must be binary type"

### ISSUE THREAD

**Issue by stbrody** [libp2p/js-libp2p-kad-dht#298]
I'm trying to register as a provider of some content to my local libp2p node by calling `libp2p.contentRouting.provide(cid)`, but I keep getting an error:
```
Error: Unknown type, must be binary type
    at Encoder.encode (/home/spencer/tempBugRepo/node_modules/multiformats/cjs/src/bases/base.js:18:13)
    at toString (/home/spencer/tempBugRepo/node_modules/uint8arrays/cjs/src/to-string.js:12:23)
    at makeProviderKey (/home/spencer/tempBugRepo/node_modules/libp2p-kad-dht/src/providers.js:224:41)
    at Providers._getProvidersMap (/home/spencer/tempBugRepo/node_modules/libp2p-kad-dht/src/providers.js:163:22)
    at /home/spencer/tempBugRepo/node_modules/libp2p-kad-dht/src/providers.js:184:32
    at run (/home/spencer/tempBugRepo/node_modules/p-queue/dist/index.js:157:104)
    at PQueue._tryToStartAnother (/home/spencer/tempBugRepo/node_modules/p-queue/dist/index.js:105:17)
    at /home/spencer/tempBugRepo/node_modules/p-queue/dist/index.js:171:18
    at new Promise (<anonymous>)
    at PQueue.add (/home/spencer/tempBugRepo/node_modules/p-queue/dist/index.js:152:16)
```

My suspicion is that there's a bug in the KadDHT implementation here: https://github.com/libp2p/js-libp2p-kad-dht/blob/3997d67134df84ae091c6fa06f479635315ee957/src/providers.js#L224.  I believe that should just be `cid.multihash` not `cid.multihash.bytes`, as `cid.multihash` is already of type `Uint8Array` and Uint8Arrays have no field named "bytes".

Minimal code example that repros the issue is available here: https://github.com/stbrody/libp2p-bug-repro

**Comment by stbrody** [comment]
Oh and in case it's relevant, tested with Node v16.13.1, NPM v8.1.2 on Ubuntu 20.04.3

**Comment by stbrody** [comment]
I guess the issue was I was using the old `cids` package instead of the newer `multiformats/cid`.  Closing
