### ISSUE TITLE
`toB58String()` function missing when activating debugging with libp2p

### ISSUE THREAD

**Issue by Alexis-ROYER** [libp2p/js-libp2p-kad-dht#314]
When activating debugging with libp2p, the following error occurs when calling `DHTContentRouting.provide()`:
```
TypeError: p.toB58String is not a function
    at Function.debug.formatters.p (...\node_modules\libp2p-kad-dht\src\utils.js:152:14)
    at ...\node_modules\debug\src\common.js:100:24
    at String.replace (<anonymous>)
    at debug (...\node_modules\debug\src\common.js:91:22)
    at DualKadDHT.provide (...\node_modules\libp2p-kad-dht\src\dual-kad-dht.js:231:9)
    at provide.next (<anonymous>)
    at drain (...\node_modules\it-drain\index.js:12:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DHTContentRouting.provide (...\node_modules\libp2p\src\dht\dht-content-routing.js:28:5)
    at async Promise.all (index 0)
```

# Configuration
- libp2p@0.36.2 (latest version as of today)
- libp2p-kad-dht@0.28.6 (pulled as a dependency of the latter)

# Steps to reproduce
- Start from [js-libp2p/blob/master/examples/peer-and-content-routing/2.js](https://github.com/libp2p/js-libp2p/blob/master/examples/peer-and-content-routing/2.js)
- Add the following at the beggining of the script :
  ```js
  const debug = require('debug')
  debug.enable('libp2p*')
  ```

**Comment by Alexis-ROYER** [comment]
First question: is this really an issue, or something I misuse?

I've noticed that js-libp2p-kad-dht has come to official releases from versions 1.0.0 to 1.0.5.
I guess that this has given birth to a new npm package [@libp2p/kad-dht](https://www.npmjs.com/package/@libp2p/kad-dht) holding versions 1.0.0 and higher, while the former [libp2p-kad-dht](https://www.npmjs.com/package/libp2p-kad-dht) holds up to version 0.28.6 only.
Is it possible to upgrade js-libp2p-kad-dht to version 1.0.5, still using js-libp2p?

Thank you very much for your help.

**Comment by Alexis-ROYER** [comment]
Here is a hack I have tuned to work around the problem (typescript code):
```Typescript
// Hack libp2p-kad-dht's logger factory.
const debug = require('debug');
const util = require('util')
const libp2pKadDhtUtils = require('libp2p-kad-dht/src/utils')

const _fixedFormatterCallback = (p) => {
  try {
    return p.toB58String();
  } catch (_err) {
    console.warn(`No such method \`toB58String()\` for object ${util.inspect(p)}: ${util.inspect(_err)}`);
    return p.toString();
  }
};

const _defaultLoggerFactory = libp2pKadDhtUtils.logger;
const _hackedLoggerFactory = (name) => {
  // Call default implementation.
  const _logger = _defaultLoggerFactory(name);

  // Fix 'debug' formatter.
  debug.formatters.p = _fixedFormatterCallback;

  return _logger;
};
libp2pKadDhtUtils.logger = _hackedLoggerFactory;
```

Here are the two kind of traces I get:
```
No such method `toB58String()` for object Uint8Array(34) [
   18,  32, 108, 128,  84, 235, 194,  51,
   47,  14,  27,  70, 139, 226, 106, 178,
   79, 224, 234, 124, 143, 183, 220, 154,
  188,  66, 251, 153,  19, 180, 233, 122,
  231, 119
]: TypeError: p.toB58String is not a function
    at Function._fixedFormatterCallback (...\js-libp2p-kad-dht#314.js:13:16)
    at ...\node_modules\debug\src\common.js:100:24
    at String.replace (<anonymous>)
    at debug (...\node_modules\debug\src\common.js:91:22)
    at DualKadDHT.provide (...\node_modules\libp2p-kad-dht\src\dual-kad-dht.js:231:9)
    at provide.next (<anonymous>)
    at drain (...\node_modules\it-drain\index.js:12:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DHTContentRouting.provide (...\node_modules\libp2p\src\dht\dht-content-routing.js:28:5)
    at async Promise.all (index 0)
```
and:
```
No such method `toB58String()` for object <Buffer 12 20 a3 8c 73 d8 ab 4f 11 18 71 79 c5 f0 86 d6 be ca 3e c2 22 6e f6 40 23 2c 94 36 c5 a1 a6 e3 60 46>: TypeError: p.toB58String is not a function
    at Function._fixedFormatterCallback (...\js-libp2p-kad-dht#314.js:13:16)
    at ...\node_modules\debug\src\common.js:100:24
    at String.replace (<anonymous>)
    at debug (...\node_modules\debug\src\common.js:91:22)
    at DualKadDHT.provide (...\node_modules\libp2p-kad-dht\src\dual-kad-dht.js:231:9)
    at provide.next (<anonymous>)
    at drain (...\node_modules\it-drain\index.js:12:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DHTContentRouting.provide (...\node_modules\libp2p\src\dht\dht-content-routing.js:28:5)
    at async Promise.all (index 0)
```
It sounds wierd to me that we get different objects while the call stacks are identical so far...

Whatever, it seems that `Uint8Array` and `Buffer` objects are sometimes passed on to the `debug.formatters.p` callback.

**Comment by mpetrunic** [comment]
> First question: is this really an issue, or something I misuse?
> 
> I've noticed that js-libp2p-kad-dht has come to official releases from versions 1.0.0 to 1.0.5. I guess that this has given birth to a new npm package [@libp2p/kad-dht](https://www.npmjs.com/package/@libp2p/kad-dht) holding versions 1.0.0 and higher, while the former [libp2p-kad-dht](https://www.npmjs.com/package/libp2p-kad-dht) holds up to version 0.28.6 only. Is it possible to upgrade js-libp2p-kad-dht to version 1.0.5, still using js-libp2p?
> 
> Thank you very much for your help.

@Alexis-ROYER  It should work if you use it with [libp2p@0.37](https://github.com/libp2p/js-libp2p/releases/tag/v0.37.0)

**Comment by Alexis-ROYER** [comment]
Thanks for the information.
I check as soon as I can and tell you back.
