### ISSUE TITLE
Test is weird

### ISSUE THREAD

**Issue by diasdavid** [libp2p/js-libp2p-kad-dht#8]
@dignifiedquire this test

```
  1) DHT find peer query:

      Uncaught AssertionError: expected 1 to deeply equal 0
      + expected - actual

      -1
      +0

      at utils.sortClosestPeers (test/index.spec.js:240:51)
      at map (src/utils.js:120:5)
      at node_modules/async/internal/map.js:32:9
      at node_modules/async/internal/once.js:12:16
      at iteratorCallback (node_modules/async/eachOf.js:60:13)
      at node_modules/async/internal/onlyOnce.js:12:16
      at node_modules/async/internal/map.js:29:13
      at exports.convertPeerId (src/utils.js:110:7)
      at setImmediate (node_modules/multihashing-async/src/utils.js:8:7)
      at Immediate.<anonymous> (node_modules/async/internal/setImmediate.js:26:16)

```

sometimes fail. If we look at the test, we can see that it sets up a random DHT leading to sometimes non predictable scenarios.

**Comment by diasdavid** [comment]
fixed in https://github.com/libp2p/js-libp2p-kad-dht/pull/25
