### ISSUE TITLE
DHT causes js-IPFS to crash

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-kad-dht#94]
Not quite sure what caused this, but it was fatal.

```
TypeError: Cannot read property 'verify' of undefined
    at validate (/path/to/ipfs/js-ipfs/node_modules/ipns/src/index.js:86:13)
    at extractPublicKey (/path/to/ipfs/js-ipfs/node_modules/ipns/src/index.js:296:7)
    at extractPublicKey (/path/to/ipfs/js-ipfs/node_modules/ipns/src/index.js:196:3)
    at Object.validate (/path/to/ipfs/js-ipfs/node_modules/ipns/src/index.js:290:5)
    at Object.func (/path/to/ipfs/js-ipfs/src/core/ipns/routing/utils.js:13:47)
    at Object.verifyRecord (/path/to/ipfs/js-ipfs/node_modules/libp2p-kad-dht/node_modules/libp2p-record/src/validator.js:32:13)
    at KadDHT._verifyRecordLocally (/path/to/ipfs/js-ipfs/node_modules/libp2p-kad-dht/src/private.js:163:28)
    at putValue (/path/to/ipfs/js-ipfs/node_modules/libp2p-kad-dht/src/rpc/handlers/put-value.js:30:9)
    at dht._add (/path/to/ipfs/js-ipfs/node_modules/libp2p-kad-dht/src/rpc/index.js:41:7)
    at utils.convertPeerId (/path/to/ipfs/js-ipfs/node_modules/libp2p-kad-dht/src/routing.js:131:7)
```

**Comment by vasco-santos** [comment]
Thanks for reporting this @achingbrain 

This should be fixed by https://github.com/ipfs/js-ipns/pull/21 . Reopen this issue if that is still a problem
